CREATE TABLE [dbo].[Todo] (
	[Id] INT NOT NULL IDENTITY(1,1),

	[Summary] NVARCHAR(256) NOT NULL,
	[Description] NVARCHAR(512) NULL,

    --[IsDeleted] [BIT] NOT NULL,

    /*AUDIT FIELDS*/
    [Created] DATETIME NOT NULL CONSTRAINT [DF__TABLE_NAME__createdon] DEFAULT (GETDATE()),
    [CreatedBy] UNIQUEIDENTIFIER NOT NULL,
    [LastModified] DATETIME NULL,
    [LastModifiedBy] UNIQUEIDENTIFIER NULL,
    [ChangeSource] NVARCHAR(128) NULL
) ON [PRIMARY]

--primary key definition
ALTER TABLE [dbo].[Todo] ADD CONSTRAINT [PK__Todo] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]

--CREATE NONCLUSTERED INDEX [IX__TABLE_NAME__INDEXED_COLUMN] ON [dbo].[TABLE_NAME] ([INDEXED_COLUMN]) ON [AN_MAIN_IDX]

--ALTER TABLE [dbo].[TABLE_NAME] ADD CONSTRAINT [FK__TABLE_NAME__OTHER_TABLE] FOREIGN KEY ([FOREIGN_KEY_COLUMN]) REFERENCES [dbo].[OTHER_TABLE] ([FOREIGN_KEY_COLUMN])